### ISSUE TITLE
Does not stretch in height

### ISSUE THREAD

**Issue by EliteNoob002** [tamius-han/ultrawidify#219]
**Describe the bug**
Does not stretch in height, so instead of removing black bars, it just stretches the width. I only checked on YouTube.

**To Reproduce**
I open a video with a custom resolution, but it only stretches in width

**Expected behavior**
The video should also stretch in height

**Screenshots**
![image](https://user-images.githubusercontent.com/120501360/213688982-803a6b56-3e59-49a8-bee2-e6e6f4bb1d99.png)

![image](https://user-images.githubusercontent.com/120501360/213688871-4f87ba04-c38b-4689-9bb1-f724af99e357.png)

**Browser and OS**
 * Browser/browser version: Chrome 109.0.5414.75
 * Operating system: Windows 11
 * Ultrawidify version:  5.1.5

**Comment by tamius-han** [comment]
Hi,

quick questions (since it'll be a while before I get to a windows/chrome
combo):

* Is default stretch mode (popup -> extension settings and popup -> site
settings) set to "Normal" and "Default"?

If this option is set to 'basic,' the image will get stretched like that.

* Go to `chrome://flags/` and search for `Choose ANGLE graphics backend`.
What's the selected value?

Throughout 2021, Chrome and related browsers had a bug where videos bigger
than the browser window were being displayed incorrectly by the browser.
Fix for that problem was to set Chrome's ANGLE backend to `OpenGL` or
`D3D9`, however that issue should have been fixed about a year ago.

V V pet., 20. jan. 2023 ob 12:56 je oseba EliteNoob002 <
***@***.***> napisala:

**Comment by EliteNoob002** [comment]
Stretch mode was selected "Normal" and "Default"

"Choose ANGLE graphics backend" was "Default", but after I changed to "OpenGL" it works fine. Maybe this bug is back

**Comment by TechnoStone** [comment]
Also confirming this bug on Edge 109.0.1518.61, Windows 11 (build 10.0.22621.1105), Ultrawidify 5.1.5 (both ms edge store and chrome webstore versions are affected (tested separately with one being deleted while other was tested)). Stretch mode was selected "Normal" and "Default" by default extension settings.
Tried "Choose ANGLE graphics backend" different settings with these results:
• Default - stretched
• OpenGL - stretched
• D3D11 - stretched
• D3D9 - works as should
• D3D11on12 - stretched

**Comment by tamius-han** [comment]
> • OpenGL - stretched

_huh?_ Now that's funny to see, because in Chrome OpenGL works just fine. I guess I'll need to update the popup on Edge version (again), thanks for pointing this out.

Anyway, I've put instructions on how the problem can be fixed into the extension popup (about as much as I can do here). Update has passed Chrome Web Store review and is up, chances are most people got it already.

For Edge, the update is still pending review. It will probably be up by the end of the week (judging by my past experience with Edge addon store).
